#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=`getApplication`

runApplication blockMesh
#runApplication snappyHexMesh -overwrite
cp -r 0.orig 0 

runApplication setFields

runApplication decomposePar
mpirun -np 12  --hostfile machines --rankfile rankfile interFoam -parallel > log.interFoam 
runApplication reconstructPar
echo Reconstruct case... 
reconstructPar > reconstructPar.log 
echo Reconstruct complete. 
#rm -rf pro*    

#------------------------------------------------------------------------------
